apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit-web # Must match labels in deployment_web.yaml
  ports:
    - name: web
      protocol: TCP
      port: 80         # Internal cluster port
      targetPort: 8501 # Container Port Streamlit is running on
      nodePort: 30085  # External access port (30000-32767)
